// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import MiroAppController from "./miro_app_controller"
import MiroFormController from "./miro_form_controller"


application.register("miro-form", MiroFormController)
application.register("hello", HelloController)
application.register("miro-app", MiroAppController)